version: '3.7'

services:
  rabbit:
    image: rabbitmq:3.7-management
    container_name: rabbit
    restart: on-failure
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:10.11
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '0123456kKk'
  library:
    build: ./library
    container_name: library
    restart: on-failure
    expose:
      - 8080
    ports: ['8080:8080']
    depends_on:
      - postgres
      - rabbit
      - historian-checker
  mail_sender:
    build: ./mail_sender
    container_name: mail_sender
    restart: always
    expose:
      - 8081
    ports: ['8081:8081']
    depends_on:
      - rabbit
      - library
  historian-checker:
    build: ./historian_checker
    container_name: historian-checker
    restart: on-failure
    expose:
      - 8082
    depends_on:
      - postgres
    ports: ['8082:8082']
